Feature/yarn
nhsuk/profiles pull request #122
Opened 2017-04-21 11:01 UTC by st3v3nhunt

2017-04-21 12:55 UTC, markysoft commented on scripts/start
> +docker-compose up --build --force-recreate
missing profiles-frontend on the up command

2017-04-21 12:55 UTC, markysoft requested changes
The start command is not working for me.
I get an error:
 ./node_modules/.bin/bunyan: not found

The start command is running three containers, rather than just the required two.

2017-04-21 13:22 UTC, st3v3nhunt commented
@markysoft Yeah sorry about that. Pretty stupid thing to overlook. Not sure what the fix for bunyan is. I'll have a look at it.

2017-04-21 19:30 UTC, st3v3nhunt commented
@markysoft Should be good to go now:

* The error with Bunyan is sorted (the binary wasn't in the same place since the move to yarn)
* The specific service required to run the app has been specified
* The readme has been updated and points to the scripts

2017-04-24 08:29 UTC, markysoft approved these changes

2017-04-24 08:29 UTC, merged