:information_desk_person: update single time table
nhsuk/profiles pull request #151
Opened 2017-05-30 12:06 UTC by ajthomascouk

2017-05-31 09:26 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-151.dev.beta.nhschoices.net)

2017-05-31 09:35 UTC, ajthomascouk commented
@alex-colbeck thoughts?

2017-05-31 11:02 UTC, alex-colbeck submitted a review, later dismissed
Looks good to me. Saves loads of space on mobile.

2017-05-31 13:27 UTC, beseven commented
@ajthomascouk - can you rebase please?

2017-05-31 14:00 UTC, beseven submitted a review, later dismissed
Looks ok to me, can you show the team @ajthomascouk through a screenshare/etc?

2017-06-01 10:14 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-151.dev.beta.nhschoices.net)

2017-06-01 11:34 UTC, markysoft requested changes
Exceptional opening times are forced to use the single session styling regardless of how many sessions giving formatting issues.

2017-06-01 11:34 UTC, markysoft commented on app/lib/continuousTimeUtils.js
> +    } else if ((time.sessions.length === 1) || (isOneSession === true)) {
This logic seems to be in place to always force the exceptional opening time to use the single session styling, regardless of how many sessions there are.

This leads to bad formatting on the page, i.e. http://profiles-pr-151.dev.beta.nhschoices.net/gp-surgeries/41823

2017-06-01 12:33 UTC, ajthomascouk commented on app/lib/continuousTimeUtils.js
> +    } else if ((time.sessions.length === 1) || (isOneSession === true)) {
Well spotted. I set it to `||` as it wasn't adding the `one-session` class for "normal" opening hours. I've made that work by setting the flag to true in [`openingTimesMapper.js`](https://github.com/nhsuk/profiles/pull/151/commits/cec41ce6a225501377e05f017653c321d4603818#diff-8e199386d5cabc6984ff1b2c134f9236)

2017-06-01 12:38 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-151.dev.beta.nhschoices.net)

2017-06-02 08:49 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-151.dev.beta.nhschoices.net)

2017-06-02 09:03 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-151.dev.beta.nhschoices.net)

2017-06-02 10:15 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-151.dev.beta.nhschoices.net)

2017-06-02 10:36 UTC, alex-colbeck approved these changes
Great work team 👍

2017-06-02 10:37 UTC, markysoft approved these changes

2017-06-02 10:38 UTC, alex-colbeck commented
🔥  good work.

2017-06-02 10:38 UTC, merged