Feature/content changes
nhsuk/profiles pull request #153
Opened 2017-05-30 16:50 UTC by beseven

2017-05-30 16:55 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-153.dev.beta.nhschoices.net)

2017-05-31 06:51 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-153.dev.beta.nhschoices.net)

2017-05-31 08:32 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-153.dev.beta.nhschoices.net)

2017-05-31 08:37 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-153.dev.beta.nhschoices.net)

2017-05-31 09:49 UTC, ajthomascouk requested changes
Looks good, just one question about the use of `include` rather than `equal` in the tests.

2017-05-31 09:49 UTC, ajthomascouk commented on test/integration/openingTimes.js
> +          expect($('h2.opening-times').last().text().trim()).to.include('When GPs see patients');
Should `include` not be `equal` in this test?

2017-05-31 10:09 UTC, beseven commented on test/integration/openingTimes.js
> +          expect($('h2.opening-times').last().text().trim()).to.include('When GPs see patients');
Based on the history it seems that at some point it only covered part of the message which could happen again. It might be a matter of style.

2017-05-31 10:15 UTC, beseven commented on test/integration/openingTimes.js
> +          expect($('h2.opening-times').last().text().trim()).to.include('When GPs see patients');
Made tests more specific here: https://github.com/nhsuk/profiles/pull/141/commits/7d6a45fd6b1e3be76d04a187667af8fdf432c446

2017-05-31 10:16 UTC, ajthomascouk approved these changes

2017-05-31 10:16 UTC, merged