Feature/front end
nhsuk/profiles pull request #17
Opened 2017-02-20 14:44 UTC by ajthomascouk

2017-02-21 10:36 UTC, st3v3nhunt commented
@ajthomascouk Some conflicts need resolving please

2017-02-22 15:09 UTC, st3v3nhunt requested changes
Conflicts to resolve.

Does the geolocation stuff need to be included?

There are a bunch of image and js files in the `app/views` dir. Should they be in `/public` only?

It looks very much like a copy and paste. There are ways to share the code between repos - have these been considered? And what is the rationale for taking that approach?

A bunch of tests are failing on the build. Mostly because the test is along the lines of `expect(res.text).to.equal(${some-word});`. They should work ok if they are changed to `expect(res.text).to.contain(${some-word});`

2017-02-22 15:09 UTC, st3v3nhunt commented on Dockerfile
> +RUN [ "npm", "run" ]
Does this need to be here?

2017-02-22 15:09 UTC, st3v3nhunt commented on app/views/includes/foot.nunjucks
> +<script src="{{ SITE_ROOT }}/js/geolocation.js" type="text/javascript"></script>
Where is this used i.e. `geolocation.js`

2017-02-22 15:09 UTC, st3v3nhunt commented on app/views/search.nunjucks
> +{% extends 'layout.nunjucks' %}
Is this file required?

2017-02-22 15:09 UTC, st3v3nhunt commented on config/routes.js
> -router.get('/', (req, res) => {
Why has this gone?

2017-02-22 15:09 UTC, st3v3nhunt commented on docker-compose.yml
> -
Leave this empty line in

2017-02-22 15:09 UTC, st3v3nhunt commented on public/js/geolocation.js
> +jQuery(function($) {
Is this file required?

2017-02-22 18:50 UTC, st3v3nhunt commented
![](https://github.trello.services/images/mini-trello-icon.png) [style front-end for GP profile pages](https://trello.com/c/RpZoL5iS/840-style-front-end-for-gp-profile-pages)

2017-02-23 10:03 UTC, ajthomascouk commented on Dockerfile
> +RUN [ "npm", "run" ]
Im not sure on this one. Could do with your input on this.

2017-02-23 10:04 UTC, ajthomascouk commented on app/views/includes/foot.nunjucks
> +<script src="{{ SITE_ROOT }}/js/geolocation.js" type="text/javascript"></script>
Removed this. It was left over from a copy and paste dump.

2017-02-23 10:10 UTC, ajthomascouk commented on app/views/search.nunjucks
> +{% extends 'layout.nunjucks' %}
@st3v3nhunt - I guess its not if this app is only one page?

2017-02-23 10:11 UTC, ajthomascouk commented on config/routes.js
> -router.get('/', (req, res) => {
I put it back in. I wasn't sure that it was actually needed/useful.

2017-02-23 10:11 UTC, ajthomascouk commented on public/js/geolocation.js
> +jQuery(function($) {
Removed

2017-02-23 10:51 UTC, st3v3nhunt commented
@ajthomascouk Is this ok to close now?

2017-02-23 10:54 UTC, ajthomascouk commented
No longer needed.

2017-02-23 10:54 UTC, closed without merging