:camera: add cache-control for non error pages
nhsuk/profiles pull request #184
Opened 2017-07-05 15:26 UTC by markysoft

Add cache-control headers for successfully served pages.
The 400 range and 500 range are considered errors, and will not be cached.

2017-07-05 15:31 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-184.dev.beta.nhschoices.net)

2017-07-06 08:00 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-184.dev.beta.nhschoices.net)

2017-07-10 13:04 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-184.dev.beta.nhschoices.net)

2017-07-10 13:16 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-184.dev.beta.nhschoices.net)

2017-07-12 15:51 UTC, st3v3nhunt requested changes
As discussed, it would be good to have the ability for different resource types to have different cache lengths. This is especially true given the JS and CSS assets are accessed with the query string parameter and so could be cached for 1 year.

Potentially, having different cache lengths based on status codes might be useful.

Another thought, with this current implementation everything is being cached as public which is fine for the moment but might not be so good if anything personalised was added. Currently, this is by default so if something was personalised it might not be obvious the cache control would need to be set to private. Perhaps an opt-in model?

Also, having some tests would be good.

2017-07-17 14:30 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-184.dev.beta.nhschoices.net)

2017-07-17 14:37 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-184.dev.beta.nhschoices.net)

2017-07-18 07:06 UTC, st3v3nhunt requested changes
A few comments on the test.

2017-07-18 07:06 UTC, st3v3nhunt commented on test/integration/smartCache.js
> +        expect(res).to.not.have.header('Cache-Control', 'public, max-age=60');
Can this check just for the header rather than the value as well? It will make it more likely to catch the addition of the header.

2017-07-18 07:06 UTC, st3v3nhunt commented on test/integration/smartCache.js
> +const chai = require('chai');
Conventionally, modules are included first (this applies to both `chai` and `chai-http`).

2017-07-18 07:06 UTC, st3v3nhunt commented on test/integration/smartCache.js
> +describe('smartCache', () => {
I know the name of the module is `smartCache` but if that changes this also needs to change (along with this file name). In order to keep the tests valid through a renaming of the module if this was `describe('Cache-Control headers', ... )` it wouldn't need to change.

2017-07-18 07:06 UTC, st3v3nhunt commented on test/integration/smartCache.js
> +  it('should set cache-control header for valid page', (done) => {
I know the value of `CACHE_TIMEOUT_SECONDS` is implicitly tested here but it would be good to have that included in the description of the test.

2017-07-18 11:41 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-184.dev.beta.nhschoices.net)

2017-07-18 11:46 UTC, st3v3nhunt approved these changes
LGTM

2017-07-18 11:47 UTC, merged