Feature/performance tests
nhsuk/profiles pull request #192
Opened 2017-07-19 10:47 UTC by markysoft

Add simple parameterised JMeter test for performance test

2017-07-19 10:52 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-19 11:43 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-19 15:33 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-19 16:30 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-19 16:33 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-20 07:02 UTC, beseven commented on test/performance/README.md
> +| `hostname`                       | URL of server to test                                              | profiles.dev.beta.nhschoices.net|
Usually, performance tests are done on the staging environment as it's deemed closer to the production configuration. In our case, it should have multiple images per app and theoretically, that should take the load.

2017-07-20 07:07 UTC, beseven commented on test/performance/README.md
> +*Note:* The path to JMeter may differ depending on your installation location.
Is the approach of running the perf-tests in the container not the same anymore? https://github.com/nhsuk/nhsuk-rancher-templates/compare/feature/pharmacy-finder-perf-tests?expand=1

2017-07-20 07:08 UTC, st3v3nhunt reviewed
A few comments on the `README`. I'll be looking at the test next.

2017-07-20 07:08 UTC, st3v3nhunt commented on test/performance/README.md
> +# Profiles Performance Test
Could probably just have the heading as `Performance Testing`

2017-07-20 07:08 UTC, st3v3nhunt commented on test/performance/README.md
> +| `csvfile`                        | csv data file of choices ID to use, either `ids_100.csv`, `ids_1200.csv`, or `ids_all.csv` (9000+), allowing a number of different GP pages to be visited during t
Missing `v` from default value `ids_100.cs` ➡️  `ids_100.csv`

2017-07-20 07:08 UTC, st3v3nhunt commented on test/performance/README.md
> +/usr/local/bin/jmeter/jmeter -n -t  ./profiles.jmx -Jhostname=*hostname* -Jusers=*users* -Jrampup=*rampup* -Jduration=*duration* -Jthroughput=*throughput* Jcsvfile=*csvfile* -l profiles.jtl
Surrounding this with backticks would help differentiate the command from the text.

Perhaps have a script with the default values in `./scripts/test-perf` to allow easy running locally?

2017-07-20 08:16 UTC, st3v3nhunt requested changes
Why is there no use of a Cookie Manager?

I've made some tweaks in a PR #193

2017-07-20 08:16 UTC, st3v3nhunt commented on test/performance/profiles.jmx
> +        <stringProp name="ThreadGroup.ramp_time">${__P(rampup,20)}</stringProp>
Why a 20 second ramp-up period?

2017-07-20 08:16 UTC, st3v3nhunt commented on test/performance/profiles.jmx
> +        <stringProp name="ThreadGroup.num_threads">${__P(users,5)}</stringProp>
Why 5 users?

2017-07-20 08:18 UTC, st3v3nhunt commented
@markysoft Can there just be a single data file of all of the ids?

2017-07-20 08:27 UTC, markysoft commented on test/performance/README.md
> +| `hostname`                       | URL of server to test                                              | profiles.dev.beta.nhschoices.net|
Good spot, it runs against staging on the triggered performance tests, I'll update the default.

2017-07-20 08:37 UTC, markysoft commented on test/performance/README.md
> +*Note:* The path to JMeter may differ depending on your installation location.
The goal of this PR is to add a JMeter tests to be used by the Teamcity performance dashboards. The information in the readme is to describe the parameters used, and provide assistance if you want to run them locally. 

It's not meant to replace any other approaches, just to describe how you might run them if you'd like to.

2017-07-20 09:45 UTC, markysoft commented on test/performance/README.md
> +/usr/local/bin/jmeter/jmeter -n -t  ./profiles.jmx -Jhostname=*hostname* -Jusers=*users* -Jrampup=*rampup* -Jduration=*duration* -Jthroughput=*throughput* Jcsvfile=*csvfile* -l profiles.jtl
You can either have italics from the *, or back ticks, they don't seem to play well together . I think italicising the variable names is better than the code formatting.

The scope of this work is to provide a JUnit test for the Teamcity performance checks. Providing a way to run performance tests locally is a big topic, as already mentioned in @beseven 's comment above. 

In my mind the only reason to run them locally is when editing the JMX file.

2017-07-20 09:49 UTC, markysoft commented on test/performance/profiles.jmx
> +        <stringProp name="ThreadGroup.ramp_time">${__P(rampup,20)}</stringProp>
These figures are small defaults used when running locally. On the TeamCity build they are overridden with longer times, more users, etc with scenario settings suggested by the performance specialists in line with other projects.

2017-07-20 10:05 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-20 10:45 UTC, markysoft commented
RE: having a single data file - the profiles data changes on a daily basis. If a practice is removed or changes ID then the test will return a 404, which is considered a failure on the performance test, so using the full list can give false negatives.

One approach to mitigate this would be to request a list of valid IDs before the test starts.
For now a small curated list of IDs is provided, with the other data sets available for more intensive testing.

2017-07-20 12:44 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-20 13:01 UTC, st3v3nhunt commented on test/performance/README.md
> +| `hostname`                       | URL of server to test                                              | profiles.dev.beta.nhschoices.net|
@markysoft Did you intend to update the default `hostname`?

2017-07-20 14:41 UTC, st3v3nhunt commented on test/performance/README.md
> +/usr/local/bin/jmeter/jmeter -n -t  ./profiles.jmx -Jhostname=*hostname* -Jusers=*users* -Jrampup=*rampup* -Jduration=*duration* -Jthroughput=*throughput* Jcsvfile=*csvfile* -l profiles.jtl
Damn back ticks 🤛

2017-07-24 08:44 UTC, c2s-dev commented
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-27 09:59 UTC, c2s-dev commented
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-192.dev.beta.nhschoices.net)

2017-07-27 10:29 UTC, st3v3nhunt approved these changes

2017-07-27 10:29 UTC, merged