Feature/assert no page not found
nhsuk/profiles pull request #194
Opened 2017-07-20 14:38 UTC by st3v3nhunt

2017-07-20 14:42 UTC, c2s-dev commented
:rocket: deployment of profiles succeeded (http://profiles-pr-194.dev.beta.nhschoices.net)

2017-07-24 08:34 UTC, markysoft requested changes

2017-07-24 08:34 UTC, markysoft commented on test/performance/README.md
> +| `hostname`                         | URL of server to test
Good spot

2017-07-24 08:34 UTC, markysoft commented on test/performance/profiles.jmx
> +              <stringProp name="1235244996">Page not found</stringProp>
Could the test assert against the response code, rather than the response text?

2017-07-26 11:30 UTC, c2s-dev commented
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-194.dev.beta.nhschoices.net)

2017-07-26 11:38 UTC, st3v3nhunt commented on test/performance/profiles.jmx
> +              <stringProp name="1235244996">Page not found</stringProp>
@markysoft I've done some more testing and I don't think there needs to be an explicit check for the 404 as this is done by default. I thought the exit code was being set to non-zero when there is an assertion check but this isn't the case so it makes no difference. Hopefully TeamCity can pick up on the number of tests that have failed from the report.

2017-07-26 11:40 UTC, c2s-dev commented
:rocket: deployment of nhsuk/profiles succeeded (http://profiles-pr-194.dev.beta.nhschoices.net)

2017-07-27 10:30 UTC, st3v3nhunt commented
No longer required

2017-07-27 10:30 UTC, closed without merging