:barber: more frontend changes
nhsuk/profiles pull request #30
Opened 2017-02-24 12:12 UTC by ajthomascouk

Creating a PR so changes can be demoed.

2017-02-24 12:17 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-30.dev.c2s.nhschoices.net](http://profiles-pr-30.dev.c2s.nhschoices.net)

2017-02-24 12:32 UTC, markysoft requested changes
Seems a bit strange having a class called 'h3', and applying it to an h2 element.

Should it be called something more descriptive, like 'sub-title'?

2017-02-24 12:55 UTC, ajthomascouk commented
@markysoft I'm not to fussed what its called. I think it's clearer what we're trying to achieve from the style if its call '.h3' If we call it 'sub-title' for example, is it a H3 style or is it something else?

2017-02-27 09:15 UTC, st3v3nhunt requested changes

2017-02-27 09:15 UTC, st3v3nhunt commented on scss/c2s/c2s.scss
> +$blue: #0072c6;
If the variable is defined already within the `@import` does that make it available within this? It looks like it has been defined already in https://github.com/nhsuk/profiles/blob/db1e8a00ca69b5feb3b692a360d081670b2d9456/scss/betahealth/environment/settings/_colours.scss#L1

2017-02-27 09:15 UTC, st3v3nhunt commented on scss/c2s/c2s.scss
> +$callout-border-blue: #40ADD7;
I can't see the usage of `$callout-border-blue` or `$callout-blue`. Should the be used at https://github.com/nhsuk/profiles/pull/30/files#diff-fbb593c07f7b6259a85d6bb2324072c7R108 ?

2017-02-27 10:03 UTC, st3v3nhunt commented
@ajthomascouk I agree with @markysoft about the naming of the `h3` class on the `<h2>`. Seems like it might make it harder in the future to understand what classes should be used where.

2017-02-27 11:16 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-30.dev.c2s.nhschoices.net](http://profiles-pr-30.dev.c2s.nhschoices.net)

2017-02-27 11:19 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-30.dev.c2s.nhschoices.net](http://profiles-pr-30.dev.c2s.nhschoices.net)

2017-02-27 11:22 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-30.dev.c2s.nhschoices.net](http://profiles-pr-30.dev.c2s.nhschoices.net)

2017-02-27 12:07 UTC, ajthomascouk commented on scss/c2s/c2s.scss
> +$blue: #0072c6;
You're not wrong!

2017-02-27 12:15 UTC, ajthomascouk commented on scss/c2s/c2s.scss
> +$callout-border-blue: #40ADD7;
`.callout--blue {
    background-color: $callout-blue;
    border-left: 8px solid $callout-border-blue;
    padding: 8px 16px;
}`

2017-02-27 12:18 UTC, ajthomascouk commented on scss/c2s/c2s.scss
> +$blue: #0072c6;
> It looks like it has been defined already in 

Removed from our SCSS

2017-02-27 12:21 UTC, ajthomascouk commented
@st3v3nhunt wrote:
> I agree with @markysoft about the naming of the h3 class on the <h2>.

Okay, so sticking with BEM, how about something like `.h2--smaller`?
(cc @markysoft)

2017-02-27 12:40 UTC, st3v3nhunt commented
Re: https://github.com/nhsuk/profiles/pull/30#issuecomment-282705481

@ajthomascouk Sounds good to me. Should be good for another review once that has been done?
/cc @markysoft

2017-02-27 15:35 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-30.dev.c2s.nhschoices.net](http://profiles-pr-30.dev.c2s.nhschoices.net)

2017-02-27 16:19 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-30.dev.c2s.nhschoices.net](http://profiles-pr-30.dev.c2s.nhschoices.net)

2017-02-27 21:17 UTC, st3v3nhunt approved these changes

2017-02-27 21:18 UTC, st3v3nhunt commented
@markysoft Looks like you need to approve the changes if you have previous requested changes. I'm happy with the changes of [4ea3154](https://github.com/nhsuk/profiles/pull/30/commits/4ea315496dfe828273ab31c428c4f67e007546fb)

2017-02-28 09:38 UTC, markysoft approved these changes

2017-02-28 09:38 UTC, merged