:bullettrain_front: first round of frontend changes
nhsuk/profiles pull request #31
Opened 2017-02-27 11:21 UTC by ajthomascouk

2017-02-27 11:26 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-02-27 12:15 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-02-27 15:41 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-02-28 10:00 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-02-28 10:21 UTC, beseven requested changes

2017-02-28 10:21 UTC, beseven commented on app/views/book-appointment.nunjucks
> +      <li><a href="#">Contact reception</a></li>
anchors, please

2017-02-28 10:21 UTC, beseven commented on app/views/book-appointment.nunjucks
> +  <h2>Book an appointment online</h2>
a link, please

2017-02-28 10:34 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-02-28 10:36 UTC, beseven approved these changes

2017-02-28 10:36 UTC, beseven commented
LOTM!

2017-02-28 11:19 UTC, neilbmclaughlin approved these changes

2017-02-28 11:20 UTC, neilbmclaughlin commented
Approved against 1441bcb

2017-02-28 12:55 UTC, neilbmclaughlin commented
@ajthomascouk - rebase please

2017-02-28 13:13 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-02-28 13:14 UTC, ajthomascouk commented
@neilbmclaughlin wrote:
> rebase please

Done... Merge when you can please.

2017-03-01 07:44 UTC, st3v3nhunt requested changes
Looks like some duplication has crept in

2017-03-01 07:44 UTC, st3v3nhunt commented on scss/c2s/c2s.scss
> +$callout-border-blue: #40ADD7;
This looks like duplication, checkout lines 10 and 11 https://github.com/nhsuk/profiles/blob/1dfdc675cfa12e5157b82c055bf66edbf232d63d/scss/c2s/c2s.scss

2017-03-01 07:44 UTC, st3v3nhunt commented on public/css/nhsuk.css
> +.callout--blue { background-color: rgba(64, 173, 215, 0.1); border-left: 8px solid #40ADD7; padding: 8px 16px; }
Duplicated from line 789?
https://github.com/nhsuk/profiles/blob/1dfdc675cfa12e5157b82c055bf66edbf232d63d/public/css/nhsuk.css#L789

2017-03-01 11:13 UTC, markysoft requested changes

2017-03-01 11:13 UTC, markysoft commented on app/views/book-appointment.nunjucks
> +  <p>Contact reception: {{gp.phone}}</p>
The phone number is showing as empty on the page. In the latest schema the phone number has moved to 'contact.telephone', so needs to change if profiles 0.2.0 is being used.

2017-03-01 11:23 UTC, ajthomascouk commented on app/views/book-appointment.nunjucks
> +  <p>Contact reception: {{gp.phone}}</p>
Sorted.

2017-03-01 11:26 UTC, ajthomascouk commented on scss/c2s/c2s.scss
> +$callout-border-blue: #40ADD7;
Whoops. Sorted

2017-03-01 11:27 UTC, ajthomascouk commented on public/css/nhsuk.css
> +.callout--blue { background-color: rgba(64, 173, 215, 0.1); border-left: 8px solid #40ADD7; padding: 8px 16px; }
Sloppy.. Removed the dupe.

2017-03-01 13:45 UTC, st3v3nhunt commented
@ajthomascouk Can you rebase this when you get chance please? It isn't going to be possible to merge until, thanks!

2017-03-01 13:55 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-03-01 20:15 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-03-02 07:28 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-03-02 07:51 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-31.dev.c2s.nhschoices.net](http://profiles-pr-31.dev.c2s.nhschoices.net)

2017-03-02 08:00 UTC, st3v3nhunt approved these changes

2017-03-02 08:00 UTC, st3v3nhunt commented
@markysoft Just need your review and merge  on this now please

2017-03-02 08:01 UTC, st3v3nhunt approved these changes
Reviewed against [42ce254](https://github.com/nhsuk/profiles/pull/31/commits/dff42ce2547b62f2d30a29b45f9ccbef54ef244a)

2017-03-02 10:17 UTC, markysoft approved these changes

2017-03-02 10:18 UTC, merged