:clock3: Add reception and surgery opening times
nhsuk/profiles pull request #52
Opened 2017-03-09 16:14 UTC by markysoft

Moved GP Count logic from renderer to middleware.
Exposed opening times on profiles page.

2017-03-09 16:20 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-10 11:15 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-13 09:43 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-13 12:27 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-13 16:56 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-14 12:45 UTC, c2s-dev commented
:warning: deployment of 52 for nhsuk/profiles failed

2017-03-15 10:47 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-15 15:13 UTC, st3v3nhunt requested changes
I'm not a fan of the name `gpCountsHelper`, I'm not sure I would see that file and go
> aha, that will have a method in to work out if there are any GPs available

Suggest renaming it to `gpHelper` or something similar. I'd also be inclined to change the name of the function `gpsAvailable` to `areGpsAvailable`

I like the lib for converting times to 12 hour mode. Probably something to think about sharing in the future.

2017-03-15 15:13 UTC, st3v3nhunt commented on app/lib/parseOpeningTimes.js
> +module.exports = { parseAll, parseWeek, parseDay };
I'd prefer this spread over multiple lines as future changes are easy to see via diffs e.g.
```
module.exports = {
  parseAll,
  parseWeek,
  parseDay,
};
````

Do `parseWeek` and `parseDay` need to be exported?

2017-03-15 15:13 UTC, st3v3nhunt commented on app/lib/timeUtils.js
> +module.exports = { toAmPm };
I'd prefer this spread over multiple lines as future changes are easy to see via diffs

2017-03-15 15:13 UTC, st3v3nhunt commented on app/views/includes/opening-times.nunjucks
> +{% endif %}
Newline please

2017-03-15 15:13 UTC, st3v3nhunt commented on test/unit/lib/parseOpeningTimes.js
> +
Remove additional line please

2017-03-15 15:13 UTC, st3v3nhunt commented on test/unit/lib/parseOpeningTimes.js
> +    it('should gracefully handle missing days on opening times', () => {
Additional line please

2017-03-15 15:13 UTC, st3v3nhunt commented on test/unit/lib/timeUtils.js
> +
Remove additional line please

2017-03-15 15:13 UTC, st3v3nhunt commented on app/lib/parseOpeningTimes.js
> +  if (!allTimes) {
Use ternary to have a single return statement?

2017-03-15 15:13 UTC, st3v3nhunt commented on app/lib/parseOpeningTimes.js
> +    reception: allTimes.reception && parseWeek(allTimes.reception),
I can't see a test for the null check for either `allTimes.reception` or `allTimes.surgery` (on the following line)

2017-03-15 15:13 UTC, st3v3nhunt commented on test/unit/lib/parseOpeningTimes.js
> +      // expect(openingTimes[1]).to.equal('1:30pm to 8:00pm');
Should this be deleted?

2017-03-15 15:13 UTC, st3v3nhunt commented on test/unit/lib/parseOpeningTimes.js
> +    it('should replace contiguous times with a single message', () => {
Looks like a duplicate of https://github.com/nhsuk/profiles/pull/52/files#diff-19ef8052a34c4516c393f39bb38bb599R119

2017-03-15 15:13 UTC, st3v3nhunt commented on test/unit/lib/parseOpeningTimes.js
> +    it('should change empty array to closed message', () => {
Looks like a duplicate of https://github.com/nhsuk/profiles/pull/52/files#diff-19ef8052a34c4516c393f39bb38bb599R137

2017-03-15 15:13 UTC, st3v3nhunt commented on test/integration/openingTimes.js
> +          expect(res.text).to.include('When reception is open');
Can cheerio be used to check this text and be a bit more specific about the locator used to access it? Same goes for the line below.

2017-03-15 15:13 UTC, st3v3nhunt commented on test/integration/openingTimes.js
> +          expect(res.text).to.include('When reception is open');
Can cheerio be used to check this text and be a bit more specific about the locator used to access it? Same goes for the line below.

2017-03-15 15:13 UTC, st3v3nhunt commented on test/unit/lib/timeUtils.js
> +
Remove this line please

2017-03-15 16:01 UTC, markysoft commented on app/lib/parseOpeningTimes.js
> +module.exports = { parseAll, parseWeek, parseDay };
parseWeek and parseDay are exported to test individually

2017-03-15 16:15 UTC, markysoft commented on app/lib/parseOpeningTimes.js
> +    reception: allTimes.reception && parseWeek(allTimes.reception),
added check

2017-03-15 16:20 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-15 16:42 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-52.dev.c2s.nhschoices.net](http://profiles-pr-52.dev.c2s.nhschoices.net)

2017-03-15 17:11 UTC, st3v3nhunt approved these changes

2017-03-15 17:11 UTC, merged