:closed_lock_with_key: initial always closed logic
nhsuk/profiles pull request #64
Opened 2017-03-16 15:50 UTC by markysoft

Final changes for opening times

2017-03-16 15:56 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-64.dev.c2s.nhschoices.net](http://profiles-pr-64.dev.c2s.nhschoices.net)

2017-03-16 16:46 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-64.dev.c2s.nhschoices.net](http://profiles-pr-64.dev.c2s.nhschoices.net)

2017-03-27 08:23 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-64.dev.c2s.nhschoices.net](http://profiles-pr-64.dev.c2s.nhschoices.net)

2017-03-27 11:12 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-64.dev.c2s.nhschoices.net](http://profiles-pr-64.dev.c2s.nhschoices.net)

2017-03-27 12:12 UTC, st3v3nhunt requested changes

2017-03-27 12:12 UTC, st3v3nhunt commented on app/lib/parseOpeningTimes.js
> +  daysOfWeek.forEach((day) => {
`forEach` could be replaced with `includes` to prevent the full set being iterated.

2017-03-27 12:55 UTC, markysoft commented on app/lib/parseOpeningTimes.js
> +  daysOfWeek.forEach((day) => {
includes won't work as that matches an exact value, rather than the output of a function. Have used 'some' instead.

2017-03-27 13:01 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-64.dev.c2s.nhschoices.net](http://profiles-pr-64.dev.c2s.nhschoices.net)

2017-03-27 13:07 UTC, st3v3nhunt approved these changes

2017-03-27 13:07 UTC, st3v3nhunt commented on app/lib/parseOpeningTimes.js
> +  return daysOfWeek.some((day) => {
👍

2017-03-27 13:08 UTC, merged