Feature/3 col tables
nhsuk/profiles pull request #71
Opened 2017-03-21 10:11 UTC by ajthomascouk

2017-03-21 11:08 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-71.dev.c2s.nhschoices.net](http://profiles-pr-71.dev.c2s.nhschoices.net)

2017-03-22 12:15 UTC, st3v3nhunt requested changes
The usage of `detect-mobile-browser` for an express app looks more simple than what has been done here. Checkout https://www.npmjs.com/package/detect-mobile-browser

The file `app/lib`mobileDetect.js` isn't required. The `requires` can be updated as per the examples. I'd get rid of the test too as that is implicit in the use of the library.

2017-03-22 12:15 UTC, st3v3nhunt commented on .dockerignore
> +lib/mobileDetect.js
Does this file really not want to be deployed into the container?

2017-03-22 12:15 UTC, st3v3nhunt commented on package.json
> +    "test": "snyk test && NODE_ENV=test mocha --recursive test",
Is there a specific reason for adding `snyk test` to the `test` script? I would prefer it to not be done there as it is a relatively expensive operation and one that we are moving towards doing on `prepush` only

2017-03-22 12:15 UTC, st3v3nhunt commented on package.json
> +}
New line please

2017-03-22 13:06 UTC, ajthomascouk commented on package.json
> +    "test": "snyk test && NODE_ENV=test mocha --recursive test",
Not sure I put it there.

2017-03-22 13:07 UTC, ajthomascouk commented on .dockerignore
> +lib/mobileDetect.js
Probably put there by mistake.

2017-03-27 10:28 UTC, st3v3nhunt commented
@ajthomascouk Can you rebase and finish the changes please?

2017-03-27 11:02 UTC, ajthomascouk commented
@st3v3nhunt wrote:
> @ajthomascouk Can you rebase and finish the changes please?

Yup, had higher priorities.

2017-03-28 15:34 UTC, ajthomascouk commented
Make days bold on mobile/stacked view.

2017-03-29 18:54 UTC, ajthomascouk commented
Closing this PR and starting fresh.

2017-03-29 18:54 UTC, closed without merging