:car: title and naming of facilties, removed dupes
nhsuk/profiles pull request #77
Opened 2017-03-27 14:19 UTC by markysoft

2017-03-27 14:24 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-27 15:58 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-28 09:02 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-28 11:24 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-29 07:29 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-29 13:41 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-29 13:55 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-29 15:26 UTC, st3v3nhunt requested changes
Some small suggestions

2017-03-29 15:26 UTC, st3v3nhunt commented on app/views/includes/parking-accessibility.nunjucks
>          <li>
I know this hasn't changed here but I've changed it in PR #85 to being it all onto one line `<li>{{name}}</li>`

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +    // eslint-disable-next-line no-unused-expressions
Not needed

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +    // eslint-disable-next-line no-unused-expressions
Not needed

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +    // eslint-disable-next-line no-unused-expressions
Not needed

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +    // eslint-disable-next-line no-unused-expressions
Not needed

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +    // eslint-disable-next-line no-unused-expressions
Not needed

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +    // eslint-disable-next-line no-unused-expressions
Not needed

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +    // eslint-disable-next-line no-unused-expressions
Not needed

2017-03-29 15:26 UTC, st3v3nhunt commented on test/unit/lib/parseFacilities.js
> +          name: 'Car Parking',
Could each of these objects be compressed onto a single line? It would be easier to read from my POV. Appreciate it might not be the case for others. e.g.
```js
    const facilities = {
      parking: [
        { name: 'Car Parking', exists: 'Yes' },
        { name: 'Cycle parking', exists: 'No' },
        { name: 'Disabled parking', exists: 'Yes' }
      ],
      accessibility: [
        { name: 'Braille translation service', exists: 'Yes' },
        { name: 'Disabled parking', exists: 'Yes' }
      ],
    };
```

If agreed, it would be good to get the other objects compressed in the same way.

2017-03-29 15:26 UTC, st3v3nhunt commented on app/lib/parseFacilities.js
> +  if (parking.length === 1 && accessibility.length === 0) {
I can see this appends `is available` to the parking item but why does this need to happen only when there is one parking and no accessibility?

2017-03-29 15:47 UTC, markysoft commented on test/unit/lib/parseFacilities.js
> +          name: 'Car Parking',
not a problem with a bit of regex replace

2017-03-29 15:51 UTC, markysoft commented on app/lib/parseFacilities.js
> +  if (parking.length === 1 && accessibility.length === 0) {
It was decided with Dean and Joe that a Parking title with a single 'Car parking' entry looked strange.

Repeated 'is available' when there was more than one parking was deemed strange looking, so 'is available' is only appended when there is a single item under the parking title.

2017-03-29 15:59 UTC, c2s-dev commented
:rocket: deployed to [http://profiles-pr-77.dev.c2s.nhschoices.net](http://profiles-pr-77.dev.c2s.nhschoices.net)

2017-03-29 15:59 UTC, st3v3nhunt approved these changes
LGTM

2017-03-29 15:59 UTC, merged